### ISSUE TITLE
Where is link

### ISSUE THREAD

**Issue by viswagfx** [ItsRauf/dataminev2#23]
Where is link to invite the bot

**Comment by BachLe2000** [comment]
https://canary.discord.com/api/oauth2/authorize?client_id=507415798189654016&permissions=537315344&scope=applications.commands%20bot

**Comment by Jacob-1999** [comment]
> https://canary.discord.com/api/oauth2/authorize?client_id=507415798189654016&permissions=537315344&scope=applications.commands%20bot

Broken link.
