### ISSUE TITLE
Max invite limit reached.

### ISSUE THREAD

**Issue by WalkxCode** [ItsRauf/dataminev2#8]
The max server invite limit for the bot has been reached. You can fix this by verifying your bot on https://dis.gd/bot-verification

**Comment by Sephiths** [comment]
Still not verified ^

**Comment by definitely-not-damon** [comment]
Anyone got a server with the bot in it that they could invite me to?

**Comment by SuperDex986** [comment]
Why is it still not verified

**Comment by quaccer** [comment]
its still not verified :(

**Comment by Galaxy-Coding** [comment]
@definitely-not-damon https://discord.gg/displace has the bot

**Comment by ItsRauf** [comment]
see #10

**Comment by rosethornbush** [comment]
Got verified finally
